### ISSUE TITLE
modifyfgo的xfgo中的一些小白疑问

### ISSUE THREAD

**Issue by carssama** [heqyoufree/modifyfgo#4]
密码，更新设置关键词这两项改如何填，按照之前AnyProxy的方法设置，点击xfgo中的安装证书无法获取证书报错，直接安装证书文件上游戏进关卡会断开服务器。如果需要改端口应该修改哪里？

**Comment by heqyoufree** [comment]
密码是用来更新设置的，正确就更新，不正确就不更新。更新设置关键词就是服务器设定的，用来判别链接是否更新链接，建议用一些不常见的文字

**Comment by carssama** [comment]
但是没法获取证书啊，是我哪里错了吗，每次都没反应

**Comment by carssama** [comment]
Error:connect ETIMEDOUT 74.125****

**Comment by carssama** [comment]
[AnyProxy ERROR][2018-09-08 17:04:58]: Error: getaddrinfo ENOTFOUND com.locbytes.xfgo.signal com.locbytes.xfgo.signal:80
[AnyProxy ERROR][2018-09-08 17:05:06]: Error: connect ETIMEDOUT 74.125.204.101:80

**Comment by carssama** [comment]
发现问题所在了，你的anproxy版本的js信号服务器没改成locbytes的信号地址，locbytes的xfgo模块改了信号地址就会闪退，只有去配置文件改了才行
